plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.droidfakecam'
    compileSdk 34

    defaultConfig {
        applicationId 'com.droidfakecam'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Root access library
    implementation 'com.github.topjohnwu.libsu:core:4.0.3'
    implementation 'com.github.topjohnwu.libsu:io:4.0.3'
}
